Handling Missing Values

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("synthetic_dataset[1].csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4188 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [6]:
print(df.isnull().sum())

Category    2748
Price        174
Rating      2050
Stock       1352
Discount     392
dtype: int64

In [ ]:
#handling missing values
#1.deleting the columns with missing data but we have almost all col with missing data
#for col updated_df=df.dropna(axis=1)
#2.deleting the rows with missing data

In [7]:
updated_df=df.dropna(axis=0)

In [8]:
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 540 entries, 6 to 4343
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  540 non-null    object
 1   Price     540 non-null    float64
 2   Rating    540 non-null    float64
 3   Stock     540 non-null    object
 4   Discount  540 non-null    float64
dtypes: float64(3), object(2)
memory usage: 25.3+ KB

In [ ]:
#3.Imputation
#filling with mean(less outliners) and median(more outliners) values if numerical ,mode if categorical data

In [9]:
df['Price'].mean()

5016.970630372492

In [10]:
df['Rating'].mean()

3.0382925191086185

In [11]:
df['Discount'].mean()

24.516624685138538

In [12]:
df['Category'].mode()

0    C
Name: Category, dtype: object

In [13]:
df['Stock'].mode()

0    In Stock
Name: Stock, dtype: object

In [14]:
updated_df=df
updated_df['Price']=updated_df['Price'].fillna(df['Price'].mean())
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4362 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [15]:
updated_df=df
updated_df['Rating']=updated_df['Rating'].fillna(df['Rating'].mean())
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4362 non-null   float64
 2   Rating    4362 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [16]:
updated_df=df
updated_df['Discount']=updated_df['Discount'].fillna(df['Discount'].mean())
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4362 non-null   float64
 2   Rating    4362 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  4362 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [20]:
updated_df=df
updated_df['Category']=updated_df['Category'].fillna(df['Category'].mode()[0])
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  4362 non-null   object
 1   Price     4362 non-null   float64
 2   Rating    4362 non-null   float64
 3   Stock     3011 non-null   object
 4   Discount  4362 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [21]:
updated_df=df
updated_df['Stock']=updated_df['Stock'].fillna(df['Stock'].mode()[0])
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  4362 non-null   object
 1   Price     4362 non-null   float64
 2   Rating    4362 non-null   float64
 3   Stock     4362 non-null   object
 4   Discount  4362 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [23]:
updated_df.head(10)

  Category   Price    Rating         Stock   Discount
0        C  5548.0  1.870322      In Stock   0.000000
1        C  3045.0  4.757798      In Stock  38.000000
2        C  4004.0  3.038293      In Stock   0.000000
3        C  4808.0  1.492085      In Stock  33.000000
4        C  1817.0  3.038293  Out of Stock  23.000000
5        C  3522.0  3.038293      In Stock  24.516625
6        C   667.0  3.668341      In Stock  41.000000
7        A  7125.0  4.983998  Out of Stock   7.000000
8        A  2777.0  2.678384      In Stock   6.000000
9        C   463.0  4.626187      In Stock   3.000000

In [ ]:
#4.Forward and Backward Filling-Imputation(bfill and ffill)

In [26]:
df=pd.read_csv("synthetic_dataset[1].csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4188 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [27]:
df1=df

In [28]:
df1['Price']=df1['Price'].bfill()#backward fill filling the values backward

In [29]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4361 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [32]:
df1['Category']=df1['Category'].bfill()

In [33]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  4362 non-null   object
 1   Price     4361 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 170.5+ KB

In [34]:
df1.head(20)

   Category   Price    Rating         Stock  Discount
0         C  5548.0  1.870322           NaN       0.0
1         C  3045.0  4.757798           NaN      38.0
2         C  4004.0       NaN      In Stock       0.0
3         C  4808.0  1.492085           NaN      33.0
4         C  1817.0       NaN  Out of Stock      23.0
5         C  3522.0       NaN           NaN       NaN
6         C   667.0  3.668341      In Stock      41.0
7         A  7125.0  4.983998  Out of Stock       7.0
8         A  2777.0  2.678384      In Stock       6.0
9         A   463.0  4.626187           NaN       3.0
10        A  1151.0  2.947838           NaN       NaN
11        A  3772.0  4.890750      In Stock      45.0
12        A  7719.0  2.982242      In Stock       4.0
13        C  8416.0  1.270943           NaN      29.0
14        B  8530.0       NaN           NaN      10.0
15        A  7936.0  3.032832      In Stock      44.0
16        B  9319.0  3.479064      In Stock      28.0
17        B  2066.0  4.097464           NaN      40.0
18        D  2066.0       NaN           NaN      30.0
19        B  1784.0       NaN           NaN      12.0